version: '3.8'

services:
  rss-summarizer:
    build: .
    container_name: rss-summarizer
    volumes:
      - ./articles:/app/articles
      - ./logs:/app/logs
      - ./.env:/app/.env
      - ./config.json:/app/config.json
    environment:
      - TZ=America/New_York
    restart: always 